### ISSUE TITLE
Issue related to the width of new fonts (Droid Sans Mono and Droid Sans Mono (Resized))

### ISSUE THREAD

**Issue by tititopher68-dev** [Quint097/DWIN_Font_Tools#5]
When displaying numeric values of type abc.dd (with 2 decimal places)
The number "a" is altered. The effect is even more flagrant when it comes to a negative value -abc.dd or the number 9, 8, 6 (for "a")

To fix it:
Either reduce the width of the digits effectively,
Either modify the firmware code (I will inform @Jyers) as follows:

void CrealityDWINClass::Draw_Float(float value, uint8_t row, bool selected/*=false*/, uint8_t minunit/*=10*/) {
  uint16_t bColor = (selected) ? Select_Color : Color_Bg_Black;
  if (isnan(value)) {
    DWIN_Draw_String(false, true, DWIN_FONT_MENU, Color_White, bColor, 194 , MBASE(row), F(" NaN"));
  } else if (value < 0) {
    DWIN_Draw_FloatValue(true, true, 0, DWIN_FONT_MENU, Color_White, bColor, (minunit == 100) ? 6-log10(minunit) : 5-log10(minunit), log10(minunit), 202, MBASE(row), -value * minunit);
    DWIN_Draw_String(false, true, DWIN_FONT_MENU, Color_White, bColor, (minunit == 100) ? 186 : 194, MBASE(row), F("-"));
  }
  else {
    DWIN_Draw_FloatValue(true, true, 0, DWIN_FONT_MENU, Color_White, bColor, (minunit == 100) ? 6-log10(minunit) : 5-log10(minunit), log10(minunit), 202, MBASE(row), value * minunit);
    DWIN_Draw_String(false, true, DWIN_FONT_MENU, Color_White, bColor, (minunit == 100) ? 186 : 194, MBASE(row), F(" "));
  }
}

**Comment by Quint097** [comment]
Can you show a picture of this?
Does this happen with all font sizes or just some of them?

**Comment by Quint097** [comment]
@tititopher68-dev @Jyers
I've had a look at, what i think it is your referring to, and I can see the problem. Because of the low resolution the font is in, I won't be able to reduce the width of the font any further, as this will make them illegible.

i think that this most likely needs to be fix in the firmware.

**Comment by tititopher68-dev** [comment]
@Quint097 
That's what I thought too, so I passed the change on to Jacob.

I open a parenthesis. Would it be possible to have an encoding integrating these French accented characters (é, è, ç, à, ô, ê, û). I am modifying all the firmware to choose different language ...

**Comment by Jyers** [comment]
@tititopher68-dev I'm sure that change works well, but I should really make the formatting and negative sign dynamically space with the number of digits anyway. I'll get on that.

**Comment by tititopher68-dev** [comment]
@Quint097 
I did the formatting and negative sign dynamically space with the number of digits anyway...The result is satisfactory and works with the different FONT PACKs.

code :

void CrealityDWINClass::Draw_Float(float value, uint8_t row, bool selected/=false/, uint8_t minunit/=10/) {
uint16_t bColor = (selected) ? Select_Color : Color_Bg_Black;
uint16_t ndigits = 0;
if (!isnan(value)) ndigits = ((value == 0) || (abs(value) < 10)) ? 1 : floor(log10(abs(value))) + 1 ;
if (isnan(value)) {
DWIN_Draw_String(false, true, DWIN_FONT_MENU, Color_White, bColor, 194 , MBASE(row), F(" NaN"));
} else if (value < 0) {
DWIN_Draw_FloatValue(true, true, 0, DWIN_FONT_MENU, Color_White, bColor, (minunit == 100) ? 6-log10(minunit) : 5-log10(minunit), log10(minunit), 202, MBASE(row), -value * minunit);
DWIN_Draw_String(false, false, DWIN_FONT_MENU, Color_White, bColor, 220 - (6 * ndigits), MBASE(row), F("-"));
}
else {
DWIN_Draw_FloatValue(true, true, 0, DWIN_FONT_MENU, Color_White, bColor, (minunit == 100) ? 6-log10(minunit) : 5-log10(minunit), log10(minunit), 202, MBASE(row), value * minunit);
DWIN_Draw_String(false, false, DWIN_FONT_MENU, Color_White, bColor, 220 - (6 * ndigits), MBASE(row), F(" "));
}
}

**Comment by tititopher68-dev** [comment]
@Quint097 
Do you see that ? https://github.com/MarlinFirmware/Marlin/pull/22211/commits/d7a00b3bd61d3741b65f0ccc8589996991780d05
Perhaps an esay way to create new FONT ?

**Comment by Quint097** [comment]
I will look at it when I'm back form vacation at the beginning of august.

I'm closing this issue, because it has been solved. When I'm back form vacation, I will open a discussion about this.
